import { JobType } from "@/types/admin-career"

export const MOCK_JOBS: JobType[] = [
  {
    id: "job-1",
    title: "Software Engineer",
    companyId: "comp-1",
    companyName: "Google",
    location: "Bangalore, India",
    experienceRequired: "0-2 Years",
    jobType: "Hybrid",
    salaryRange: "₹25LPA - ₹30LPA",
    lastDate: "Jul 20, 2026",
    status: "Active",
    createdAt: "Jul 01, 2026",
    updatedAt: "Jul 01, 2026",
    createdBy: "Kiran Kendre",
    description: "We are looking for a Software Engineer to join our core search team.",
    skills: ["C++", "Python", "Algorithms", "Distributed Systems"],
    eligibility: "B.Tech/BE in CS/IT. 2026 Graduates only.",
    applyLink: "https://careers.google.com",
    tags: ["Product", "MNC", "SDE-1"]
  },
  {
    id: "job-2",
    title: "System Engineer",
    companyId: "comp-2",
    companyName: "TCS",
    location: "Pan India",
    experienceRequired: "Fresher",
    jobType: "Onsite",
    salaryRange: "₹3.36LPA - ₹7LPA",
    lastDate: "Aug 01, 2026",
    status: "Active",
    createdAt: "Jul 03, 2026",
    updatedAt: "Jul 03, 2026",
    createdBy: "Admin User",
    description: "TCS is hiring freshers for the Ninja and Digital roles.",
    skills: ["Java", "SQL", "HTML/CSS", "Aptitude"],
    eligibility: "60% or 6 CGPA across academics. All branches.",
    applyLink: "https://tcs.com/careers",
    tags: ["Mass Hiring", "IT Services"]
  },
  {
    id: "job-3",
    title: "Frontend Developer",
    companyId: "comp-4",
    companyName: "Vercel",
    location: "Remote",
    experienceRequired: "1-3 Years",
    jobType: "Remote",
    salaryRange: "$80k - $120k",
    lastDate: "Jun 30, 2026",
    status: "Expired",
    createdAt: "May 15, 2026",
    updatedAt: "Jun 30, 2026",
    createdBy: "Kiran Kendre",
    description: "Build the future of the web with Next.js and Vercel.",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    eligibility: "Strong portfolio of frontend projects.",
    applyLink: "https://vercel.com/careers",
    tags: ["Remote", "Startup", "Frontend"]
  }
]
